### ISSUE TITLE
Case sensitivity issues in the repo

### ISSUE THREAD

**Issue by AndrewMSHowe** [MickiusMousius/Rolio46Keyboard#12]
Hi, I need this keeb so badly :) But I noticed while cloning that there are some files/paths that are only distinguished by case. No doubt you're on Linux or whatevs, but anyway maybe these are duplicates anyway?

`warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'chassis/cnc/CNC Parts/Rolio CNC Tapping Specification.pdf'
  'chassis/cnc/cnc parts/Rolio CNC Tapping Specification.pdf'
  'chassis/cnc/Left.step'
  'chassis/cnc/left.step'
  'chassis/cnc/Right.step'
  'chassis/cnc/right.step'
  'chassis/electronics/Left.step'
  'chassis/electronics/left.step'
  'chassis/electronics/Right.step'
  'chassis/electronics/right.step'
  'chassis/fdm/Left.step'
  'chassis/fdm/left.step'
  'chassis/fdm/Right.step'
  'chassis/fdm/right.step'`

**Comment by MickiusMousius** [comment]
Fixed!

Thanks for pointing it out.

This is more a case of me being a bit silly, all duplicates, but MacOS and and case sensitivity can be a bit odd.

For what it's worth I already have inventory, so if you want one I can sort you out. Send an email to contact@keydio.io if you're interested.
