### ISSUE TITLE
SLS chassis - right bottom plate don't have enough space for the R3 680Ω resistor

### ISSUE THREAD

**Issue by mbiernacki89** [MickiusMousius/Rolio46Keyboard#15]
The right bottom plate (chassis/sls/fdm pla parts/right - bottom plate.stl) seems to not have enough space for one of the 680Ω resistors (marked R3). I had to carve a portion of it to make space for it.

![IMG_2779](https://github.com/user-attachments/assets/5593f4ef-1eb5-44cd-9679-210bb68a4868)

**Comment by MickiusMousius** [comment]
Ah, I’ve fixed that a long time ago.

I’ve got a lot of updated CAD models, lots of improvements have been made to the chassis and travel cases.

I think I will need to prioritise updating these repos with the newest models.

**Comment by mbiernacki89** [comment]
Ah, I'm glad I havent ordered cnc chassis right away then :)

I'll be waiting for the updates, thanks for the help and quick responses

**Comment by mbiernacki89** [comment]
Ah, I'm glad I havent ordered cnc chassis right away then :)

I'll be waiting for the updates, thanks for the help and quick responses
